# 18.02.2021: temporarily disabled as labeler keeps removing the labels
# possible related issues:
# - https://github.com/actions/labeler/issues/112
# - https://github.com/actions/labeler/issues/104

# Add 'Needs Documentation -auto-' label to indicate a change needs changes in the docs
Needs Documentation -auto-:
  - changed-files:
    -  any-glob-to-any-file: cmd/snap/**"
    -  any-glob-to-any-file: daemon/**
    -  any-glob-to-any-file: overlord/hookstate/ctlcmd/**
    -  any-glob-to-any-file: overlord/configstate/configcore/**
