name: Tests
on:
  pull_request:
    branches: [ "master", "release/**", "core-snap-security-release/**", "security-release/**", "hotfix/**" ]
  push:
    branches: [ "release/**", "core-snap-security-release/**", "security-release/**" ]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-downloads:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        use-master-push: 
          - true
          - false
        is-amd:
          - true
          - false
        is-arm:
          - true
          - false
        is-fips:
          - true
          - false
        exclude:
          - is-arm: true
            is-fips: true
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        # spread uses tags as delta reference
        fetch-depth: 0
    - name: download snap
      uses: ./.github/actions/download-snapd-snap
      with:
        use-master-push: ${{ matrix.use-master-push }}
        is-amd: ${{ matrix.is-amd }}
        is-arm: ${{ matrix.is-arm }}
        is-fips: ${{ matrix.is-fips }}
    - name: ls
      run: ls
