name: Nightly Firefox peformance tests

# on:
#   schedule:
#   - cron: "0 0 * * *"
#   workflow_dispatch:

on:
  pull_request:
    branches: [ "master", "release/**", "core-snap-security-release/**", "security-release/**", "hotfix/**" ]
  push:
    branches: [ "release/**", "core-snap-security-release/**", "security-release/**" ]

jobs:

  test-firefox-snap:
    name: Test Firefox snap
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        wget https://storage.googleapis.com/snapd-spread-tests/snapd-tests/snaps/snapd_master_amd64.snap
        sudo snap install snapd_master_amd64.snap --dangerous
        sudo snap install firefox
        sudo apt install xvfb

    - name: Run Firefox performance tests
      uses: ./.github/actions/run-firefox-performance-tests
      with:
        firefox-exec: firefox
        results-file: /tmp/snap-results.json

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: snap-results
        path: /tmp/snap-results.json

  test-firefox-binary:
    name: Test Firefox binary
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo snap install firefox
        sudo apt install xvfb

    - name: Run Firefox performance tests
      uses: ./.github/actions/run-firefox-performance-tests
      with:
        firefox-exec: /snap/firefox/current/usr/lib/firefox/firefox
        results-file: /tmp/bin-results.json

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: bin-results
        path: /tmp/bin-results.json

  compare-results:
    needs:
      - test-firefox-snap
      - test-firefox-binary
    name: Compare snap vs. binary results
    runs-on: ubuntu-latest
    steps:
    - name: Download snap results
      uses: actions/download-artifact@v4
      with:
        name: snap-results
    
    - name: Download bin results
      uses: actions/download-artifact@v4
      with:
        name: bin-results

    - name: Compare and report results
      run: |
          cat <<EOF > comparison.py
          import json
          from statistics import geometric_mean


          def calculate_overall_score(tests_json):
              scores = []
              for k, v in tests_json.items():
                  scores.append(v['metrics']['Score']['current'][0])
              return geometric_mean(scores)

          def print_individual_score_diff(snap_json, bin_json, log_file):
              with open(log_file, 'w') as f:
                  for metric, data in snap_json.items():
                      s = data['metrics']['Score']['current'][0]
                      b = bin_json[metric]['metrics']['Score']['current'][0]
                      f.write(f'metric {metric}: {b - s}\n')

          with open("snap-results.json", 'r') as f:
              snap = json.load(f)["JetStream2.0"]["tests"]
          with open("bin-results.json", 'r') as f:
              bin = json.load(f)["JetStream2.0"]["tests"]

          snap_score = calculate_overall_score(snap)
          bin_score = calculate_overall_score(bin)
          print(f'Overall score for snap {snap_score}')
          print(f'Overall score for bin {bin_score}')
          print_individual_score_diff(snap, bin, "firefox-metrics.log")

          # The bigger the overall score is, the better it is; see https://browserbench.org/JetStream2.2/index.html
          # The choice of threshold is somewhat arbitrary
          if bin_score - snap_score > 10:
            print(f'The binary is better than the snap by more than 10: {bin_score - snap_score}')
            exit(1)
          EOF
          python3 comparison.py
          cat firefox-metrics.log
